### ISSUE TITLE
Flask app

### ISSUE THREAD

**Issue by jkjunior** [wickedasp/eureka#10]
Hi.
I'm trying to use this in a Flask APP but i got this:

```
Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x7fc51630b588>
Traceback (most recent call last):
  File "run.py", line 33, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "run.py", line 23, in main
    result = await eureka.register()
  File "/home/joaokleiber/Documents/api-env/lib/python3.5/site-packages/wasp_eureka/client.py", line 158, in register
    return await self._do_req(url, method='POST', data=json.dumps(payload))
  File "/home/joaokleiber/Documents/api-env/lib/python3.5/site-packages/wasp_eureka/client.py", line 249, in _do_req
    await resp.text())
wasp_eureka.exc.EurekaException
```
Do you know how can i resolve this? Is this work for a Flask APP?

Thanks to advance.

**Comment by mattrasband** [comment]
Hi, this is written for an asyncio based application - meaning that WSGI based apps don't really fit that.
